x-db-environment: &x-db-environment
  POSTGRES_SSL_MODE: "disable"
  POSTGRES_HOST: "pg"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "db"
  POSTGRES_PASSWORD: "myAwEsOm3pa55@w0rd"
  POSTGRES_USER: "user"


x-backend-app-environment: &x-backend-app-environment
  # App
  <<: *x-db-environment

  APP_NAME: "music-streaming"
  APP_VERSION: "1.0.0"
  APP_PORT: 8080


services:
  app:
    container_name: app
    platform: linux/amd64
    environment:
      <<: *x-backend-app-environment
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - pgadmin
    ports:
      - 8080:8080
    networks:
      app_network:
        aliases:
          - app.lvh.me

  postgres:
    container_name: pg
    image: postgres:17
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      <<: *x-db-environment
    networks:
      app_network:
        aliases:
          - pg.lvh.me

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:9.5.0
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      CHECK_EMAIL_DELIVERABILITY: "False"
    ports:
      - "8000:80"
    networks:
      app_network:
        aliases:
          - pgadmin.lvh.me

networks:
  app_network:
    external: false

volumes:
  db_data: