import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Player from '../components/Player';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <main className="flex-grow">{children}</main>
        <footer className="fixed bottom-0 left-0 right-0 z-50 p-0 m-0">
          <div className="w-full">
            <Player />
          </div>
        </footer>
      </body>
    </html>
  );
}
